export const SAG_COUNTRIES = [
  { id: 'china', name: 'China', codigo: 'CHN', region: 'Asia', organism: 'GACC (General Administration of Customs of China)' },
  { id: 'eeuu', name: 'Estados Unidos', codigo: 'USA', region: 'América del Norte', organism: 'USDA-APHIS', programa: 'Programa Pre-Embarque SAG-USDA APHIS' },
  { id: 'brasil', name: 'Brasil', codigo: 'BRA', region: 'América del Sur', organism: 'MAPA - Ministerio de Agricultura y Ganadería de Brasil' },
  { id: 'corea', name: 'Corea del Sur', codigo: 'KOR', region: 'Asia', organism: 'NPQS Corea' },
  { id: 'japon', name: 'Japón', codigo: 'JPN', region: 'Asia', organism: 'MAFF Japón' },
  { id: 'peru', name: 'Perú', codigo: 'PER', region: 'América del Sur', organism: 'SENASA' },
  { id: 'mexico', name: 'México', codigo: 'MEX', region: 'América del Norte', organism: 'SENASICA' },
  { id: 'colombia', name: 'Colombia', codigo: 'COL', region: 'América del Sur', organism: 'IAS' },
  { id: 'india', name: 'India', codigo: 'IND', region: 'Asia', organism: 'Plant Quarantine' },
  { id: 'canada', name: 'Canadá', codigo: 'CAN', region: 'América del Norte', organism: 'CFIA' },
  { id: 'europa', name: 'Unión Europea', codigo: 'EU', region: 'Europa', organism: 'EFSA' },
];

export const SAG_FAMILIES = {
  carozos: { name: 'Carozos', species: ['Cereza', 'Durazno', 'Nectarín', 'Ciruela'] },
  pomaceas: { name: 'Pomáceas', species: ['Manzana', 'Pera'] },
};

export const SAG_VARIETIES = {
  Cereza: ['Lapins', 'Santina', 'Regina', 'Bing', 'Kordia', 'Sweetheart', 'Royal Rainier'],
  Manzana: ['Gala', 'Royal Gala', 'Fuji', 'Granny Smith', 'Cripps Pink', 'Pink Lady', 'Ambrosia', 'Braeburn'],
  Pera: ['Packham', 'Abate Fétel', 'Forelle', 'Coscia', 'Williams'],
  Durazno: ['September Lady', 'O\'Henry', 'Ryan Sun'],
  Nectarín: ['Arctic Queen', 'Summergrand'],
  Ciruela: ['Angeleno', 'Sapphire'],
};

export const SDP_CATEGORIES = {
  A: { name: 'Categoría A', description: 'Sin detección de plagas cuarentenarias. Monitoreo activo. Manejo fitosanitario documentado.', treatmentRequired: false },
  B: { name: 'Categoría B', description: 'Presencia controlada. Preinspección, registros y tratamiento cuando corresponda.', treatmentRequired: true, possibleTreatments: ['frio', 'fosfina', 'bromuro_metilo'] },
  C: { name: 'Categoría C', description: 'Mayor riesgo. Tratamiento obligatorio antes de exportación.', treatmentRequired: true, possibleTreatments: ['bromuro_metilo'] },
};

export const QUARANTINE_PESTS = {
  china: ['Cydia pomonella', 'Cydia molesta', 'Brevipalpus chilensis', 'Proeulia spp.'],
  eeuu: ['Cydia pomonella', 'Grapholita molesta', 'Conietzelella jordanzella', 'Spodoptera litura'],
  brasil: ['Cydia pomonella', 'Pseudococcus viburni', 'Leucinodes orbonalis'],
  corea: ['Cydia pomonella', 'Grapholita molesta'],
  japon: ['Cydia pomonella', 'Grapholita molesta', 'Conietzelella jordanzella'],
  mexico: ['Cydia molesta', 'Pseudococcus viburni', 'Proeulia auraria', 'Proeulia chrysopteris', 'Brevipalpus chilensis', 'Naupactus xanthographus'],
  peru: ['Cydia pomonella', 'Leucinodes orbonalis'],
  colombia: ['Cydia pomonella', 'Phthorimaea operculella'],
};

export const TREATMENT_TYPES = {
  frio: { name: 'Frío Cuarentenario', icon: '❄️', registro: ['Cámara de tratamiento', 'Fecha inicio', 'Fecha término', 'Temperatura registrada', 'Sensores utilizados', 'Historial temperatura'] },
  bromuro_metilo: { name: 'Bromuro de Metilo', icon: '🧪', registro: ['Cámara', 'Fecha tratamiento', 'Concentración', 'Tiempo exposición', 'Certificado'] },
  fosfina: { name: 'Fosfina', icon: '⚗️', registro: ['Cámara', 'Fecha', 'Responsable', 'Certificado'] },
  fumigacion: { name: 'Fumigación', icon: '🌫️', registro: ['Cámara', 'Fecha tratamiento', 'Concentración', 'Tiempo exposición', 'Certificado'] },
  tratamiento_temperatura: { name: 'Tratamiento de Temperatura', icon: '🌡️', registro: ['Temperatura', 'Duración', 'Fecha inicio', 'Fecha término', 'Cámara', 'Sensores', 'Historial temperatura'] },
  manejo_origen: { name: 'Manejo de Origen', icon: '🌿', registro: ['Producto aplicado', 'Fecha aplicación', 'Responsable', 'Registro campo'] },
};

export const INITIAL_PROTOCOLS = [
  // ═══════════════════ CHINA ═══════════════════
  {
    pais: 'China',
    organismo_destino: 'GACC',
    objetivo: 'Permitir la exportación de frutas chilenas cumpliendo los requisitos fitosanitarios establecidos por China y Chile.',
    familia: 'Carozos',
    producto: 'Cereza',
    variedades: ['Lapins', 'Santina', 'Regina', 'Bing', 'Kordia', 'Sweetheart', 'Royal Rainier'],
    requisitos: ['Huerto inscrito y autorizado para exportación', 'Packing autorizado', 'Sistema de trazabilidad desde huerto hasta embarque', 'Inspección SAG', 'Certificado fitosanitario SAG', 'Cumplimiento de plagas cuarentenarias establecidas por China'],
    controles: ['Monitoreo de plagas', 'Manejo fitosanitario registrado', 'Control de lote exportado'],
    tratamientos: [{ tipo: 'frio', aplica: true, registro: ['Cámara de tratamiento', 'Fecha inicio', 'Fecha término', 'Temperatura registrada', 'Sensores utilizados', 'Historial temperatura'] }],
    documentacion: ['Certificado fitosanitario SAG', 'Registro de huerto', 'Registro de planta empacadora', 'Identificación del lote', 'Registro tratamiento aplicado', 'Documentos de trazabilidad'],
    registros_obligatorios: [],
    checklist_exportacion: ['☐ Huerto inscrito', '☐ Packing autorizado', '☐ Trazabilidad verificada', '☐ Inspección SAG aprobada', '☐ Certificado SAG emitido', '☐ Tratamiento registrado'],
    plagas_controladas: QUARANTINE_PESTS.china,
    restricciones_especiales: '',
    observaciones: 'China posee protocolos específicos para cerezas desde Chile',
    vigente: true,
    version: '1.0',
  },
  {
    pais: 'China',
    familia: 'Pomáceas',
    producto: 'Manzana',
    variedades: ['Gala', 'Royal Gala', 'Fuji', 'Granny Smith', 'Cripps Pink', 'Pink Lady', 'Ambrosia'],
    requisitos: ['Huerto registrado', 'Empacadora autorizada', 'Inspección SAG', 'Certificado fitosanitario', 'Trazabilidad completa'],
    controles: ['Control de plagas cuarentenarias', 'Manejo fitosanitario documentado'],
    tratamientos: [{ tipo: 'frio', aplica: true, registro: ['Cámara de tratamiento', 'Fecha inicio', 'Fecha término', 'Temperatura registrada', 'Sensores utilizados'] }],
    documentacion: ['Certificado SAG', 'Registro SDP', 'Registro lote', 'Fecha embalaje', 'Código empacadora'],
    registros_obligatorios: [],
    checklist_exportacion: ['☐ Huerto registrado', '☐ Empacadora autorizada', '☐ Inspección SAG aprobada', '☐ Trazabilidad completa'],
    plagas_controladas: QUARANTINE_PESTS.china,
    observaciones: '',
    vigente: true,
    version: '1.0',
  },
  {
    pais: 'China',
    familia: 'Pomáceas',
    producto: 'Pera',
    variedades: ['Packham', 'Abate Fétel', 'Forelle', 'Coscia'],
    requisitos: ['Registro de origen', 'Inspección fitosanitaria', 'Certificación SAG', 'Trazabilidad'],
    controles: [],
    tratamientos: [{ tipo: 'frio', aplica: true, registro: ['Cámara', 'Fecha inicio', 'Fecha término', 'Temperatura'] }],
    documentacion: ['Certificado fitosanitario', 'Registro lote', 'Información variedad', 'Packing list'],
    registros_obligatorios: [],
    checklist_exportacion: ['☐ Registro origen', '☐ Inspección aprobada', '☐ Certificación SAG'],
    plagas_controladas: QUARANTINE_PESTS.china,
    observaciones: '',
    vigente: true,
    version: '1.0',
  },

  // ═══════════════════ ESTADOS UNIDOS ═══════════════════
  {
    pais: 'Estados Unidos',
    codigo_pais: 'USA',
    organismo_destino: 'USDA-APHIS',
    programa: 'Programa Pre-Embarque SAG-USDA APHIS',
    objetivo: 'Permitir el ingreso de frutas frescas chilenas cumpliendo las regulaciones fitosanitarias establecidas por Estados Unidos.',
    descripcion_protocolo: [
      'Los productos frescos autorizados deben cumplir requisitos fitosanitarios definidos por USDA-APHIS.',
      'Cuando corresponde se realiza inspección conjunta SAG-USDA APHIS en Chile.',
      'Los productores, sitios de producción y plantas pueden requerir registro previo.',
    ],
    familia: 'Carozos',
    producto: 'Cereza',
    variedades: ['Lapins', 'Santina', 'Regina', 'Bing', 'Kordia', 'Sweetheart', 'Royal Rainier'],
    requisitos: ['Productor registrado SAG', 'Planta empacadora registrada', 'Trazabilidad del lote', 'Inspección fitosanitaria', 'Certificado fitosanitario SAG'],
    controles: [],
    tratamientos: [
      { tipo: 'tratamiento_temperatura', aplica: true, registro: ['Temperatura', 'Duración', 'Fecha inicio', 'Fecha término', 'Cámara', 'Sensores', 'Historial temperatura'] },
      { tipo: 'fumigacion', aplica: 'Cuando requisito de ingreso lo indique', registro: ['Cámara', 'Fecha tratamiento', 'Concentración', 'Tiempo exposición', 'Certificado'] },
    ],
    documentacion: ['Certificado fitosanitario SAG', 'Declaraciones adicionales', 'Registro productor', 'Registro planta', 'Registro lote', 'Packing list', 'Registro tratamiento', 'Documento inspección SAG-USDA'],
    registros_obligatorios: [
      { tipo: 'Sitio de producción', campos: ['codigo_productor', 'ubicacion', 'especie', 'variedad', 'superficie', 'estado_registro'] },
      { tipo: 'Planta empacadora', campos: ['codigo_planta', 'razon_social', 'direccion', 'estado_autorizacion'] },
    ],
    checklist_exportacion: ['☐ Productor registrado', '☐ Planta registrada', '☐ Lote identificado', '☐ Variedad registrada', '☐ Inspección aprobada', '☐ Certificado SAG emitido', '☐ Tratamiento realizado si corresponde', '☐ Documentación completa'],
    plagas_controladas: QUARANTINE_PESTS.eeuu,
    restricciones_especiales: '',
    observaciones: 'Programa Pre-Embarque SAG-USDA APHIS',
    vigente: true,
    version: '1.0',
  },
  {
    pais: 'Estados Unidos',
    familia: 'Carozos',
    producto: 'Nectarín',
    variedades: [],
    requisitos: ['Registro productor', 'Inspección SAG', 'Cumplimiento requisitos USDA'],
    controles: [],
    tratamientos: [{ tipo: 'tratamiento_temperatura', aplica: true, registro: ['Temperatura', 'Duración', 'Fecha inicio', 'Fecha término'] }],
    documentacion: ['Certificado fitosanitario SAG', 'Registro productor', 'Packing list'],
    registros_obligatorios: [
      { tipo: 'Sitio de producción', campos: ['codigo_productor', 'ubicacion', 'especie', 'variedad', 'superficie', 'estado_registro'] },
    ],
    checklist_exportacion: ['☐ Productor registrado', '☐ Inspección aprobada', '☐ Documentación completa'],
    plagas_controladas: QUARANTINE_PESTS.eeuu,
    observaciones: '',
    vigente: true,
    version: '1.0',
  },
  {
    pais: 'Estados Unidos',
    familia: 'Carozos',
    producto: 'Durazno',
    variedades: [],
    requisitos: ['Certificación fitosanitaria', 'Control de plagas', 'Trazabilidad'],
    controles: [],
    tratamientos: [{ tipo: 'tratamiento_temperatura', aplica: true, registro: ['Temperatura', 'Duración', 'Fecha inicio', 'Fecha término'] }],
    documentacion: ['Certificado fitosanitario SAG', 'Trazabilidad'],
    checklist_exportacion: ['☐ Certificación emitida', '☐ Control plagas verificado', '☐ Trazabilidad OK'],
    plagas_controladas: QUARANTINE_PESTS.eeuu,
    observaciones: '',
    vigente: true,
    version: '1.0',
  },
  {
    pais: 'Estados Unidos',
    familia: 'Carozos',
    producto: 'Ciruela',
    variedades: [],
    requisitos: ['Inspección fitosanitaria', 'Certificado SAG'],
    controles: [],
    tratamientos: [],
    documentacion: ['Certificado SAG', 'Inspección fitosanitaria'],
    checklist_exportacion: ['☐ Inspección aprobada', '☐ Certificado emitido'],
    plagas_controladas: QUARANTINE_PESTS.eeuu,
    observaciones: '',
    vigente: true,
    version: '1.0',
  },
  {
    pais: 'Estados Unidos',
    familia: 'Pomáceas',
    producto: 'Manzana',
    variedades: ['Gala', 'Royal Gala', 'Fuji', 'Granny Smith', 'Cripps Pink', 'Pink Lady'],
    requisitos: ['Registro origen', 'Control fitosanitario', 'Inspección', 'Certificado SAG'],
    controles: [],
    tratamientos: [{ tipo: 'tratamiento_temperatura', aplica: true, registro: ['Temperatura', 'Duración', 'Fecha inicio', 'Fecha término', 'Cámara'] }],
    documentacion: ['Certificado SAG', 'Registro SDP', 'Registro lote', 'Packing list'],
    registros_obligatorios: [
      { tipo: 'Sitio de producción', campos: ['codigo_productor', 'ubicacion', 'especie', 'variedad', 'superficie', 'estado_registro'] },
    ],
    checklist_exportacion: ['☐ Productor registrado', '☐ Inspección aprobada', '☐ Certificado SAG emitido'],
    plagas_controladas: QUARANTINE_PESTS.eeuu,
    observaciones: '',
    vigente: true,
    version: '1.0',
  },
  {
    pais: 'Estados Unidos',
    familia: 'Pomáceas',
    producto: 'Pera',
    variedades: ['Packham', 'Abate Fétel', 'Forelle'],
    requisitos: ['Registro lote', 'Inspección fitosanitaria', 'Certificado SAG'],
    controles: [],
    tratamientos: [{ tipo: 'tratamiento_temperatura', aplica: true, registro: ['Temperatura', 'Duración', 'Fecha inicio', 'Fecha término'] }],
    documentacion: ['Certificado SAG', 'Registro lote', 'Packing list'],
    checklist_exportacion: ['☐ Lote registrado', '☐ Inspección aprobada', '☐ Certificado emitido'],
    plagas_controladas: QUARANTINE_PESTS.eeuu,
    observaciones: '',
    vigente: true,
    version: '1.0',
  },

  // ═══════════════════ BRASIL ═══════════════════
  {
    pais: 'Brasil',
    organismo_destino: 'MAPA - Ministerio de Agricultura y Ganadería de Brasil',
    objetivo: 'Permitir la exportación de frutas frescas chilenas cumpliendo los requisitos fitosanitarios establecidos por Brasil y Chile.',
    descripcion_protocolo: [
      'Los productos exportados deben cumplir los requisitos fitosanitarios establecidos por Brasil.',
      'Cada envío debe contar con certificación fitosanitaria SAG Chile.',
      'Debe existir trazabilidad desde origen hasta el embarque.',
    ],
    familia: 'Pomáceas',
    producto: 'Manzana',
    variedades: ['Gala', 'Royal Gala', 'Fuji', 'Granny Smith', 'Cripps Pink', 'Pink Lady', 'Ambrosia', 'Braeburn'],
    requisitos: ['Huerto registrado', 'Control fitosanitario', 'Registro de lote', 'Inspección SAG', 'Certificado fitosanitario'],
    controles: [],
    tratamientos: [
      { tipo: 'tratamiento_temperatura', aplica: 'Según requisito específico del producto', registro: ['Temperatura', 'Duración', 'Fecha inicio', 'Fecha término', 'Cámara', 'Registro sensores'] },
      { tipo: 'manejo_origen', aplica: true, registro: ['Producto aplicado', 'Fecha aplicación', 'Responsable', 'Registro campo'] },
    ],
    documentacion: ['Certificado fitosanitario SAG', 'Registro productor', 'Registro planta empacadora', 'Identificación lote', 'Packing list', 'Información especie', 'Información variedad', 'Fecha embalaje', 'Código empacadora', 'Registro trazabilidad'],
    registros_obligatorios: [],
    checklist_exportacion: ['☐ Productor registrado', '☐ Lote identificado', '☐ Variedad declarada', '☐ Control fitosanitario realizado', '☐ Inspección SAG aprobada', '☐ Certificado SAG emitido', '☐ Documentación completa'],
    plagas_controladas: ['Cydia molesta', 'Brevipalpus chilensis', 'Proeulia spp.', 'Pseudococcus spp.'],
    restricciones_especiales: '',
    observaciones: 'Protocolo estándar SAG Chile-Brasil para pomáceas',
    vigente: true,
    version: '1.0',
  },
  {
    pais: 'Brasil',
    familia: 'Pomáceas',
    producto: 'Pera',
    variedades: ['Packham', 'Abate Fétel', 'Forelle', 'Coscia'],
    requisitos: ['Registro productor', 'Identificación lote', 'Inspección fitosanitaria', 'Certificado SAG'],
    controles: [],
    tratamientos: [
      { tipo: 'tratamiento_temperatura', aplica: 'Según requisito específico', registro: ['Temperatura', 'Duración', 'Fecha inicio', 'Fecha término', 'Cámara', 'Registro sensores'] },
    ],
    documentacion: ['Certificado fitosanitario SAG', 'Registro productor', 'Identificación lote', 'Packing list', 'Información especie', 'Información variedad'],
    checklist_exportacion: ['☐ Productor registrado', '☐ Lote identificado', '☐ Inspección SAG aprobada', '☐ Certificado SAG emitido'],
    plagas_controladas: ['Cydia molesta', 'Brevipalpus chilensis', 'Proeulia spp.', 'Pseudococcus spp.'],
    observaciones: '',
    vigente: true,
    version: '1.0',
  },
  {
    pais: 'Brasil',
    familia: 'Carozos',
    producto: 'Cereza',
    variedades: ['Lapins', 'Santina', 'Regina', 'Bing', 'Kordia', 'Sweetheart'],
    requisitos: ['Registro productor', 'Control de plagas', 'Trazabilidad', 'Inspección SAG', 'Certificado fitosanitario'],
    controles: [],
    tratamientos: [
      { tipo: 'tratamiento_temperatura', aplica: 'Según requisito específico', registro: ['Temperatura', 'Duración', 'Fecha inicio', 'Fecha término', 'Cámara', 'Registro sensores'] },
      { tipo: 'manejo_origen', aplica: true, registro: ['Producto aplicado', 'Fecha aplicación', 'Responsable', 'Registro campo'] },
    ],
    documentacion: ['Certificado fitosanitario SAG', 'Registro productor', 'Identificación lote', 'Packing list', 'Información especie', 'Información variedad'],
    checklist_exportacion: ['☐ Productor registrado', '☐ Lote identificado', '☐ Control fitosanitario realizado', '☐ Inspección SAG aprobada', '☐ Certificado SAG emitido'],
    plagas_controladas: ['Cydia molesta', 'Brevipalpus chilensis', 'Proeulia spp.', 'Pseudococcus spp.'],
    observaciones: '',
    vigente: true,
    version: '1.0',
  },
  {
    pais: 'Brasil',
    familia: 'Carozos',
    producto: 'Nectarín',
    variedades: [],
    requisitos: ['Control fitosanitario', 'Certificado SAG', 'Registro lote'],
    controles: [],
    tratamientos: [{ tipo: 'tratamiento_temperatura', aplica: 'Según requisito', registro: ['Temperatura', 'Duración', 'Fecha inicio', 'Fecha término'] }],
    documentacion: ['Certificado SAG', 'Registro lote', 'Packing list'],
    checklist_exportacion: ['☐ Control fitosanitario realizado', '☐ Certificado SAG emitido', '☐ Documentación completa'],
    plagas_controladas: ['Cydia molesta', 'Brevipalpus chilensis', 'Proeulia spp.', 'Pseudococcus spp.'],
    observaciones: '',
    vigente: true,
    version: '1.0',
  },
  {
    pais: 'Brasil',
    familia: 'Carozos',
    producto: 'Durazno',
    variedades: [],
    requisitos: ['Control plagas', 'Inspección', 'Certificación fitosanitaria'],
    controles: [],
    tratamientos: [{ tipo: 'tratamiento_temperatura', aplica: 'Según requisito', registro: ['Temperatura', 'Duración', 'Fecha inicio', 'Fecha término'] }],
    documentacion: ['Certificado fitosanitario SAG', 'Registro lote', 'Packing list'],
    checklist_exportacion: ['☐ Control plagas verificado', '☐ Inspección aprobada', '☐ Certificación emitida'],
    plagas_controladas: ['Cydia molesta', 'Brevipalpus chilensis', 'Proeulia spp.', 'Pseudococcus spp.'],
    observaciones: '',
    vigente: true,
    version: '1.0',
  },
  {
    pais: 'Brasil',
    familia: 'Carozos',
    producto: 'Ciruela',
    variedades: [],
    requisitos: ['Trazabilidad', 'Inspección SAG', 'Certificado fitosanitario'],
    controles: [],
    tratamientos: [],
    documentacion: ['Certificado SAG', 'Packing list', 'Registro lote'],
    checklist_exportacion: ['☐ Trazabilidad verificada', '☐ Inspección aprobada', '☐ Certificado emitido'],
    plagas_controladas: ['Cydia molesta', 'Brevipalpus chilensis', 'Proeulia spp.', 'Pseudococcus spp.'],
    observaciones: '',
    vigente: true,
    version: '1.0',
  },

  // ═══════════════════ COREA DEL SUR ═══════════════════
  {
    pais: 'Corea del Sur',
    organismo_destino: 'NPQS Corea',
    familia: 'Carozos',
    producto: 'Cereza',
    variedades: ['Lapins', 'Regina', 'Santina', 'Bing', 'Kordia', 'Sweetheart'],
    requisitos: ['Certificado SAG', 'Inspección fitosanitaria', 'Control plagas cuarentenarias'],
    controles: [],
    tratamientos: [{ tipo: 'frio', aplica: true, registro: ['Cámara', 'Fecha inicio', 'Fecha término', 'Temperatura'] }],
    documentacion: ['Certificado SAG', 'Packing list', 'Registro lote'],
    checklist_exportacion: ['☐ Certificado SAG', '☐ Inspección OK', '☐ Control plagas'],
    plagas_controladas: QUARANTINE_PESTS.corea,
    observaciones: '',
    vigente: true,
    version: '1.0',
  },
  {
    pais: 'Corea del Sur',
    familia: 'Pomáceas',
    producto: 'Manzana',
    variedades: ['Gala', 'Royal Gala', 'Fuji', 'Granny Smith', 'Cripps Pink', 'Pink Lady'],
    requisitos: ['Certificado SAG', 'Inspección fitosanitaria', 'Control plagas cuarentenarias'],
    controles: [],
    tratamientos: [{ tipo: 'frio', aplica: true, registro: ['Cámara', 'Fecha inicio', 'Fecha término', 'Temperatura'] }],
    documentacion: ['Certificado SAG', 'Packing list', 'Registro lote'],
    checklist_exportacion: ['☐ Certificado SAG', '☐ Inspección OK'],
    plagas_controladas: QUARANTINE_PESTS.corea,
    observaciones: '',
    vigente: true,
    version: '1.0',
  },
  {
    pais: 'Corea del Sur',
    familia: 'Pomáceas',
    producto: 'Pera',
    variedades: ['Packham', 'Abate Fétel', 'Forelle'],
    requisitos: ['Certificado SAG', 'Inspección fitosanitaria', 'Control plagas'],
    controles: [],
    tratamientos: [{ tipo: 'frio', aplica: true, registro: ['Cámara', 'Fecha inicio', 'Fecha término', 'Temperatura'] }],
    documentacion: ['Certificado SAG', 'Packing list'],
    checklist_exportacion: ['☐ Certificado SAG', '☐ Inspección OK'],
    plagas_controladas: QUARANTINE_PESTS.corea,
    observaciones: '',
    vigente: true,
    version: '1.0',
  },

  // ═══════════════════ JAPÓN ═══════════════════
  {
    pais: 'Japón',
    organismo_destino: 'MAFF Japón',
    familia: 'Carozos',
    producto: 'Cereza',
    variedades: ['Lapins', 'Regina', 'Santina', 'Bing', 'Kordia', 'Sweetheart', 'Royal Rainier'],
    requisitos: ['Certificado SAG', 'Cumplimiento MAFF', 'Inspección fitosanitaria'],
    controles: [],
    tratamientos: [{ tipo: 'frio', aplica: true, registro: ['Cámara', 'Fecha inicio', 'Fecha término', 'Temperatura'] }],
    documentacion: ['Certificado SAG', 'Packing list', 'Registro lote'],
    checklist_exportacion: ['☐ Certificado SAG', '☐ MAFF OK', '☐ Inspección aprobada'],
    plagas_controladas: QUARANTINE_PESTS.japon,
    observaciones: 'Tratamientos según protocolo específico MAFF',
    vigente: true,
    version: '1.0',
  },
  {
    pais: 'Japón',
    familia: 'Pomáceas',
    producto: 'Manzana',
    variedades: ['Gala', 'Royal Gala', 'Fuji', 'Granny Smith', 'Cripps Pink', 'Pink Lady'],
    requisitos: ['Certificado SAG', 'Cumplimiento MAFF', 'Inspección fitosanitaria'],
    controles: [],
    tratamientos: [{ tipo: 'frio', aplica: true, registro: ['Cámara', 'Fecha inicio', 'Fecha término', 'Temperatura'] }],
    documentacion: ['Certificado SAG', 'Packing list', 'Registro lote'],
    checklist_exportacion: ['☐ Certificado SAG', '☐ MAFF OK'],
    plagas_controladas: QUARANTINE_PESTS.japon,
    observaciones: '',
    vigente: true,
    version: '1.0',
  },
  {
    pais: 'Japón',
    familia: 'Carozos',
    producto: 'Nectarín',
    variedades: [],
    requisitos: ['Certificado SAG', 'Cumplimiento MAFF', 'Inspección fitosanitaria'],
    controles: [],
    tratamientos: [{ tipo: 'frio', aplica: true, registro: ['Cámara', 'Fecha inicio', 'Fecha término'] }],
    documentacion: ['Certificado SAG', 'Packing list'],
    checklist_exportacion: ['☐ Certificado SAG', '☐ MAFF OK'],
    plagas_controladas: QUARANTINE_PESTS.japon,
    observaciones: '',
    vigente: true,
    version: '1.0',
  },
  {
    pais: 'Japón',
    familia: 'Carozos',
    producto: 'Ciruela',
    variedades: [],
    requisitos: ['Certificado SAG', 'Cumplimiento MAFF', 'Inspección fitosanitaria'],
    controles: [],
    tratamientos: [],
    documentacion: ['Certificado SAG', 'Packing list'],
    checklist_exportacion: ['☐ Certificado SAG', '☐ MAFF OK'],
    plagas_controladas: QUARANTINE_PESTS.japon,
    observaciones: '',
    vigente: true,
    version: '1.0',
  },

  // ═══════════════════ PERÚ ═══════════════════
  {
    pais: 'Perú',
    organismo_destino: 'SENASA',
    familia: 'Pomáceas',
    producto: 'Manzana',
    variedades: ['Gala', 'Royal Gala', 'Fuji', 'Granny Smith', 'Cripps Pink', 'Pink Lady'],
    requisitos: ['Certificado fitosanitario SAG', 'Inspección', 'Trazabilidad'],
    controles: [],
    tratamientos: [],
    documentacion: ['Certificado SAG', 'Registro lote', 'Packing list'],
    checklist_exportacion: ['☐ Certificado SAG', '☐ Inspección OK', '☐ Trazabilidad'],
    plagas_controladas: QUARANTINE_PESTS.peru,
    observaciones: '',
    vigente: true,
    version: '1.0',
  },
  {
    pais: 'Perú',
    familia: 'Pomáceas',
    producto: 'Pera',
    variedades: ['Packham', 'Abate Fétel', 'Forelle', 'Williams'],
    requisitos: ['Certificado fitosanitario SAG', 'Inspección', 'Trazabilidad'],
    controles: [],
    tratamientos: [],
    documentacion: ['Certificado SAG', 'Registro lote', 'Packing list'],
    checklist_exportacion: ['☐ Certificado SAG', '☐ Inspección OK'],
    plagas_controladas: QUARANTINE_PESTS.peru,
    observaciones: '',
    vigente: true,
    version: '1.0',
  },
  {
    pais: 'Perú',
    familia: 'Carozos',
    producto: 'Cereza',
    variedades: ['Lapins', 'Regina', 'Santina', 'Bing', 'Kordia', 'Sweetheart'],
    requisitos: ['Certificado fitosanitario SAG', 'Inspección', 'Trazabilidad'],
    controles: [],
    tratamientos: [],
    documentacion: ['Certificado SAG', 'Registro lote', 'Packing list'],
    checklist_exportacion: ['☐ Certificado SAG', '☐ Inspección OK'],
    plagas_controladas: QUARANTINE_PESTS.peru,
    observaciones: '',
    vigente: true,
    version: '1.0',
  },

  // ═══════════════════ MÉXICO ═══════════════════
  {
    pais: 'México',
    organismo_destino: 'SENASICA',
    familia: 'Pomáceas',
    producto: 'Manzana',
    variedades: ['Gala', 'Royal Gala', 'Fuji', 'Granny Smith', 'Cripps Pink', 'Pink Lady', 'Ambrosia', 'Braeburn'],
    requisitos: ['Certificado fitosanitario SAG', 'Registro SDP', 'Inspección SAG-OVO', 'Registro tratamiento frío', 'Certificado lote', 'Información variedad', 'Fecha embalaje', 'Código empacadora'],
    controles: [],
    tratamientos: [{ tipo: 'frio', aplica: true, registro: ['Cámara', 'Fecha inicio', 'Fecha término', 'Temperatura', 'Sensores'] }],
    documentacion: ['Certificado fitosanitario SAG', 'Registro SDP', 'Inspección SAG-OVO', 'Certificado tratamiento frío', 'Certificado lote', 'Especie y variedad', 'Fecha de embalaje', 'Código de empacadora', 'Registro de trazabilidad'],
    checklist_exportacion: ['☐ Certificado SAG', '☐ SDP registrado', '☐ Inspección aprobada', '☐ Tratamiento frío OK', '☐ Lote certificado', '☐ Variedad identificada', '☐ Fecha embalaje', '☐ Código empacadora'],
    plagas_controladas: QUARANTINE_PESTS.mexico,
    observaciones: 'Protocolo estándar SAG Chile-México para pomáceas',
    vigente: true,
    version: '1.0',
  },
  {
    pais: 'México',
    familia: 'Pomáceas',
    producto: 'Pera',
    variedades: ['Packham', 'Abate Fétel', 'Forelle', 'Williams'],
    requisitos: ['Certificado fitosanitario SAG', 'Registro SDP', 'Inspección SAG-OVO', 'Certificado lote'],
    controles: [],
    tratamientos: [{ tipo: 'frio', aplica: true, registro: ['Cámara', 'Fecha inicio', 'Fecha término', 'Temperatura'] }],
    documentacion: ['Certificado fitosanitario SAG', 'Registro SDP', 'Inspección SAG-OVO', 'Certificado lote'],
    checklist_exportacion: ['☐ Certificado SAG', '☐ SDP', '☐ Inspección OK', '☐ Lote certificado'],
    plagas_controladas: QUARANTINE_PESTS.mexico,
    observaciones: '',
    vigente: true,
    version: '1.0',
  },
  {
    pais: 'México',
    familia: 'Carozos',
    producto: 'Cereza',
    variedades: ['Lapins', 'Regina', 'Santina', 'Bing', 'Kordia', 'Sweetheart'],
    requisitos: ['Certificado fitosanitario SAG', 'Registro SDP', 'Inspección SAG-OVO'],
    controles: [],
    tratamientos: [{ tipo: 'frio', aplica: true, registro: ['Cámara', 'Fecha inicio', 'Fecha término', 'Temperatura'] }],
    documentacion: ['Certificado SAG', 'Packing list', 'Registro lote', 'Tratamiento frío'],
    checklist_exportacion: ['☐ Certificado SAG', '☐ SDP', '☐ Inspección OK'],
    plagas_controladas: QUARANTINE_PESTS.mexico,
    observaciones: '',
    vigente: true,
    version: '1.0',
  },

  // ═══════════════════ COLOMBIA ═══════════════════
  {
    pais: 'Colombia',
    familia: 'Pomáceas',
    producto: 'Manzana',
    variedades: ['Gala', 'Royal Gala', 'Fuji', 'Granny Smith'],
    requisitos: ['Certificado fitosanitario SAG', 'Inspección', 'Trazabilidad'],
    controles: [],
    tratamientos: [],
    documentacion: ['Certificado SAG', 'Registro lote', 'Packing list'],
    checklist_exportacion: ['☐ Certificado SAG', '☐ Inspección OK'],
    plagas_controladas: QUARANTINE_PESTS.colombia,
    observaciones: '',
    vigente: true,
    version: '1.0',
  },

  // ═══════════════════ INDIA ═══════════════════
  {
    pais: 'India',
    familia: 'Pomáceas',
    producto: 'Manzana',
    variedades: ['Gala', 'Royal Gala', 'Fuji', 'Granny Smith', 'Cripps Pink', 'Pink Lady'],
    requisitos: ['Certificado fitosanitario SAG', 'Inspección', 'Trazabilidad', 'Cumplimiento requisitos India'],
    controles: [],
    tratamientos: [{ tipo: 'frio', aplica: true, registro: ['Cámara', 'Fecha inicio', 'Fecha término', 'Temperatura'] }],
    documentacion: ['Certificado SAG', 'Registro lote', 'Packing list'],
    checklist_exportacion: ['☐ Certificado SAG', '☐ Inspección OK', '☐ India compliance'],
    plagas_controladas: QUARANTINE_PESTS.india || [],
    observaciones: '',
    vigente: true,
    version: '1.0',
  },
];

export const DEFAULT_DOCUMENT_CHECKLIST = [
  { id: 'certificado_sag', label: 'Certificado fitosanitario SAG', required: true },
  { id: 'registro_sdp', label: 'Registro SDP', required: true },
  { id: 'inspeccion_sag', label: 'Inspección SAG', required: true },
  { id: 'certificado_tratamiento', label: 'Certificado tratamiento frío', required: false },
  { id: 'certificado_lote', label: 'Certificado de lote', required: true },
  { id: 'especie_variedad', label: 'Especie y variedad', required: true },
  { id: 'fecha_embalaje', label: 'Fecha de embalaje', required: true },
  { id: 'codigo_empacadora', label: 'Código de empacadora', required: true },
  { id: 'registro_trazabilidad', label: 'Registro de trazabilidad', required: true },
  { id: 'packing_list', label: 'Packing list', required: true },
];

export function getDefaultProtocolTemplate() {
  return {
    pais: '', codigo_pais: '', organismo_destino: '', familia: '', producto: '',
    objetivo: '', descripcion_protocolo: [],
    variedades: [], requisitos: [], controles: [], tratamientos: [],
    documentacion: [], registros_obligatorios: [], checklist_exportacion: [],
    plagas_controladas: [], restricciones_especiales: '', observaciones: '',
    vigente: true, version: '1.0', fecha_actualizacion: new Date().toISOString(),
  };
}

export function findProtocolLocal(producto, variedad, pais) {
  return INITIAL_PROTOCOLS.find(p =>
    p.pais === pais && p.producto === producto && p.vigente === true &&
    (p.variedades.includes(variedad) || p.variedades.length === 0)
  ) || null;
}
